version: '3.8'

services:
  backend:
    build: ./backend
    container_name: device-farm-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - FRONTEND_URL=http://localhost:3000
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
      - /dev/bus/usb:/dev/bus/usb
    devices:
      - /dev/bus/usb
    privileged: true
    restart: unless-stopped
    networks:
      - device-farm

  frontend:
    build: ./frontend
    container_name: device-farm-frontend
    ports:
      - "3000:80"
    environment:
      - VITE_API_URL=http://localhost:5000
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - device-farm

networks:
  device-farm:
    driver: bridge